export const ConfigApp = {
  APP_NAME: "APP_NAME",
  VND_TO_CREDIT: "VND_TO_CREDIT",
  USD_TO_CREDIT: "USD_TO_CREDIT",
  MAX_CAMPAIGN: "MAX_CAMPAIGN",
  LINK_TRAFFIC_COST: "LINK_TRAFFIC_COST",
  DIRECT_LINK_COST: "DIRECT_LINK_COST",
  KEYWORD_TRAFFIC_COST: "KEYWORD_TRAFFIC_COST"
};
